# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from smolagents_crew.swarm.proto import swarm_pb2 as swarm__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in swarm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SwarmNodeServiceStub(object):
    """Service definition for SwarmNode
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/swarm.SwarmNodeService/RegisterNode',
                request_serializer=swarm__pb2.NodeInfo.SerializeToString,
                response_deserializer=swarm__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.ExecuteTask = channel.unary_unary(
                '/swarm.SwarmNodeService/ExecuteTask',
                request_serializer=swarm__pb2.TaskMessage.SerializeToString,
                response_deserializer=swarm__pb2.TaskResult.FromString,
                _registered_method=True)
        self.UpdateStatus = channel.unary_unary(
                '/swarm.SwarmNodeService/UpdateStatus',
                request_serializer=swarm__pb2.NodeStatus.SerializeToString,
                response_deserializer=swarm__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/swarm.SwarmNodeService/Heartbeat',
                request_serializer=swarm__pb2.NodeInfo.SerializeToString,
                response_deserializer=swarm__pb2.NodeStatus.FromString,
                _registered_method=True)


class SwarmNodeServiceServicer(object):
    """Service definition for SwarmNode
    """

    def RegisterNode(self, request, context):
        """Register node with manager
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTask(self, request, context):
        """Execute task on node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Update node status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat to maintain connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwarmNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=swarm__pb2.NodeInfo.FromString,
                    response_serializer=swarm__pb2.NodeStatus.SerializeToString,
            ),
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=swarm__pb2.TaskMessage.FromString,
                    response_serializer=swarm__pb2.TaskResult.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=swarm__pb2.NodeStatus.FromString,
                    response_serializer=swarm__pb2.NodeStatus.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=swarm__pb2.NodeInfo.FromString,
                    response_serializer=swarm__pb2.NodeStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swarm.SwarmNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swarm.SwarmNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SwarmNodeService(object):
    """Service definition for SwarmNode
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarm.SwarmNodeService/RegisterNode',
            swarm__pb2.NodeInfo.SerializeToString,
            swarm__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarm.SwarmNodeService/ExecuteTask',
            swarm__pb2.TaskMessage.SerializeToString,
            swarm__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarm.SwarmNodeService/UpdateStatus',
            swarm__pb2.NodeStatus.SerializeToString,
            swarm__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swarm.SwarmNodeService/Heartbeat',
            swarm__pb2.NodeInfo.SerializeToString,
            swarm__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
